#smallrain_back服务 默认值配置
#请勿改动 env 变量值
smallrain: 
  wechat:   #微信基本信息配置
    token: 
      env: WECHAT_API_TOKEN
      value: SMALL_RAIN_BACK_APPLICATION
    appId: 
      env: WECHAT_API_APPID
      value: wxb126148c95009448
    appsecret: 
      env:  WECHAT_API_APPSECRET
      value: 749abe2fc4af0c5f3f70d95d92c2fcc6
    accessTokenUrl: 
      env: WECHAT_API_ACCESSTOKENURL
      value: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
    menusCreateUrl: 
      env: WECHAT_API_MENUSCREATEURL
      value: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
    menusGetUrl: 
       env: WECHAT_API_MENUSGETURL
       value: https://api.weixin.qq.com/cgi-bin/menu/get?access_token=ACCESS_TOKEN
    menusDeleteUrl: 
      env: WECHAT_API_MENUSDELETEURL
      value: https://api.weixin.qq.com/cgi-bin/menu/delete?access_token=ACCESS_TOKEN
 
  tuling:   #图灵机器人接口介入
    apiUrl: 
      env: TULING_API_URL
      value: http://openapi.tuling123.com/openapi/api/v2
    apiKey: 
      env: TULING_API_KEY
      value: 6bb2f01f653e441887170ecdee3df869
    userId: 
      env: TULING_API_USER
      value: 347456
  #ftp 服务器配置
  ftp:
    localFtp: 
      env: FTP_ISLOCAL
      value: false
    host: 
      env: FTP_HOST
      value: 106.12.204.7
    port: 
      env: FTP_PORT
      value: 21
    username: 
      env: FTP_USERNAME
      value: smallrain
    password: 
      env: FTP_PASSWORD
      value: wy16894255
    rootPath: 
      env: FTP_ROOT_PATH
      value:  /www/wwwroot/smallrain
    connectTimeOut: #ftp 连接超时时间 毫秒
      env: FTP_CONNECT_TIMEOUT
      value:  5000  
    bufferSize:  #缓冲区大小
      env: FTP_BUFFER_SIZE
      value:  1024  
    fileType:   #传输数据格式 2 --  binary 二进制数据
      env: FTP_FILE_TYPE
      value:  2 
    dateTimeOut: 
      env: FTP_DATA_TIMEOUT
      value: 5000
    controlEncoding:
      env: FTP_ENCODING
      value:  utf-8
    useEPSVwithIPv4: 
      env: FTP_ USE_EPSV_WITH_IPV4
      value:  false
    passiveMode: 
      env: FTP_PASSIVE_MODE
      value:  true