#线上环境，数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smallrain_back?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  config: classpath:log_back/logback-prod.xml
  
#自定义配置项
app:
  smallrain:
    dommainName: http://www.smallrain.top  #服务域名
    maxFileSize: 128 #最大文件上传大小
    maxRequestSize: 512 #总上传数据总大小
    
# ftp 配置 
ftp:
  host: localhost