#tomcat配置
server:
  use-forward-headers: true
  port: 8999
  address: 127.0.0.1
  contextPath:  
  tomcat: 
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port

#线上环境，数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smallrain_back?characterEncoding=utf-8&useSSL=false
    username: smallrain
    password: wy16894255
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  config: classpath:log_back/logback-prod.xml
  
#自定义配置项
app:
  smallrain:
    dommainName: http://www.smallrain.top #服务域名
    maxFileSize: 128 #最大文件上传大小
    maxRequestSize: 512 #总上传数据总大小
    
# ftp 配置 
ftp:
  localFtp: true  #ftp服务器是否安装在本地
  host: 106.12.204.7