#tomcat配置
server:
  use-forward-headers: true
  port: ${SMALLRAINPORT:8090}
  address: 127.0.0.1
  contextPath:  ${CONTEXTPATH:/back/index}
  tomcat: 
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port

#线上环境，数据库配置
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/smallrain_back?characterEncoding=utf-8&useSSL=false}
    username: ${MYSQL_USER:smallrain}
    password: ${MYSQL_PASSWORD :wy16894255}
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  config: classpath:log_back/logback-prod.xml
  
#自定义配置项
app:
  smallrain:
    dommainName: ${SMALLRAIN_HOST:http://www.smallrain.top} #服务域名,最后不加/
    maxFileSize: 128 #最大文件上传大小
    maxRequestSize: 512 #总上传数据总大小
    tempFileDir: ${TEMPFILEDIR:/tmp/smalrain/}   #临时文件存放目录
    
# ftp 配置 
ftp:
  localFtp: ${ISLOCALFTP:true}  #ftp服务器是否安装在本地
  host: ${FTPHOST:106.12.204.7}