#默认使用配置
spring:
  application:
    name: smallrain-back
  profile:
    active: local
    
#服务配置
server:
  port: 80
  address: 0.0.0.0

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.wangying.samllrain.entity
  mapperLocations: classpath*:/mapper/*Mapper.xml

#微信基本信息配置
wechat: 
  token: SMALL_RAIN_BACK_APPLICATION
  appId: wxb126148c95009448
  appsecret: 749abe2fc4af0c5f3f70d95d92c2fcc6
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  menusCreateUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
  menusGetUrl: https://api.weixin.qq.com/cgi-bin/menu/get?access_token=ACCESS_TOKEN
  menusDeleteUrl: https://api.weixin.qq.com/cgi-bin/menu/delete?access_token=ACCESS_TOKEN
    

#数据库连接池 druid 配置
appdata:
  druid:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5  #初始化大小，最小，最大
    minIdle: 5
    maxActive: 20
    maxWait: 60000  #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000  #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true  #打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j  #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true  #合并多个DruidDataSource的监控数据
