#本地环境，数据库配置
spring:
  datasource:
    url: jdbc:mysql://106.12.204.7:3306/smallrain_back?characterEncoding=utf-8&useSSL=false
    username: root
    password: wy16894255
    driver-class-name: com.mysql.jdbc.Driver
#日志文件地址配置    
logging:
  config: classpath:log_back/logback-local.xml
  
#自定义配置项
app:
  smallrain:
    dommainName: http://localhost:80  #服务域名
    maxFileSize: 128 #最大文件上传大小
    maxRequestSize: 512 #总上传数据总大小
    
# ftp 配置 
ftp:
  host: 106.12.204.7