#默认使用配置
spring:
  application:
    name: smallrain-back
  profiles:
    active: prod
  freemarker:
    # 设置模板后缀名
    suffix: .html
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    template-encoding: UTF-8
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
    
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.wangying.samllrain.entity
  mapperLocations: classpath*:/mapper/*Mapper.xml,/mapper/extend/*Mapper.xml



 
#自定义配置
appdata:
  druid:  #数据库连接池 druid 配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5  #初始化大小，最小，最大
    minIdle: 5
    maxActive: 20
    maxWait: 60000  #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 3000  #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true  #打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j  #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true  #合并多个DruidDataSource的监控数据
         
#自定义配置项
app:
  smallrain:
    defaultResourceGroup: ef3bcee0c4ab445ea045c796456e144d    #默认资源组ID
    