package com.wangying.smallrain.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.wangying.smallrain.entity.BaseConfigs;

@Mapper
public interface BaseConfigsMapper {
    /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table base_configs
   * @mbg.generated
   */
  int deleteByPrimaryKey(String key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table base_configs
   * @mbg.generated
   */
  int insert(BaseConfigs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table base_configs
   * @mbg.generated
   */
  int insertSelective(BaseConfigs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table base_configs
   * @mbg.generated
   */
  BaseConfigs selectByPrimaryKey(String key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table base_configs
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(BaseConfigs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table base_configs
   * @mbg.generated
   */
  int updateByPrimaryKey(BaseConfigs record);

    /**
     * select all config 
     * @return
     */
    List<BaseConfigs> selectAllConfig();
}