package com.wangying.smallrain.dao;

import org.apache.ibatis.annotations.Mapper;

import com.wangying.smallrain.entity.MenuRole;

@Mapper
public interface MenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated
     */
    int insert(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated
     */
    int insertSelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated
     */
    MenuRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuRole record);
}