package com.wangying.smallrain.dao;

import java.util.List;

import com.wangying.smallrain.entity.ResourceGroup;

public interface ResourceGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_group
     *
     * @mbggenerated
     */
    int insert(ResourceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_group
     *
     * @mbggenerated
     */
    int insertSelective(ResourceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_group
     *
     * @mbggenerated
     */
    ResourceGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourceGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourceGroup record);
    
    List<ResourceGroup> selectAllRecords();
    
    int selectAllCount();
    
    int addResourceCount(int count,String id);
    
}