package com.wangying.smallrain.entity;

/**
 * 用于持久化一些可更改配置
 * @author wangying.dz3
 *
 */
public class BaseConfigs {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column base_configs.key
   * @mbg.generated
   */
  private String key;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column base_configs.value
   * @mbg.generated
   */
  private String value;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column base_configs.description
   * @mbg.generated
   */
  private String description;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column base_configs.label
   * @mbg.generated
   */
  private String label;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column base_configs.key
   * @return  the value of base_configs.key
   * @mbg.generated
   */
  public String getKey() {
    return key;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column base_configs.key
   * @param key  the value for base_configs.key
   * @mbg.generated
   */
  public void setKey(String key) {
    this.key = key == null ? null : key.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column base_configs.value
   * @return  the value of base_configs.value
   * @mbg.generated
   */
  public String getValue() {
    return value;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column base_configs.value
   * @param value  the value for base_configs.value
   * @mbg.generated
   */
  public void setValue(String value) {
    this.value = value == null ? null : value.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column base_configs.description
   * @return  the value of base_configs.description
   * @mbg.generated
   */
  public String getDescription() {
    return description;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column base_configs.description
   * @param description  the value for base_configs.description
   * @mbg.generated
   */
  public void setDescription(String description) {
    this.description = description == null ? null : description.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column base_configs.label
   * @return  the value of base_configs.label
   * @mbg.generated
   */
  public String getLabel() {
    return label;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column base_configs.label
   * @param label  the value for base_configs.label
   * @mbg.generated
   */
  public void setLabel(String label) {
    this.label = label == null ? null : label.trim();
  }
  
}