package com.wangying.smallrain.entity;

public class ResourceGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_group.id
     *
     * @mbggenerated
     */
    private String id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_group.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_group.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_group.resource_count
     *
     * @mbggenerated
     */
    private Integer resourceCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_group.id
     *
     * @return the value of resource_group.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_group.id
     *
     * @param id the value for resource_group.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_group.name
     *
     * @return the value of resource_group.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_group.name
     *
     * @param name the value for resource_group.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_group.description
     *
     * @return the value of resource_group.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_group.description
     *
     * @param description the value for resource_group.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_group.resource_count
     *
     * @return the value of resource_group.resource_count
     *
     * @mbggenerated
     */
    public Integer getResourceCount() {
        return resourceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_group.resource_count
     *
     * @param resourceCount the value for resource_group.resource_count
     *
     * @mbggenerated
     */
    public void setResourceCount(Integer resourceCount) {
        this.resourceCount = resourceCount;
    }
}